language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
before_script:
  - npm install -g bower grunt-cli
  - bower install
after_script:
  - cat "coverage/PhantomJS 1.9.8 (Windows 7)/lcov.info" | codeclimate
services: mongodb
